---
- name: Install bash
  homebrew:
    name: bash
    state: latest
  tags:
    - bash
    - pkg

- name: Install bash-completion
  homebrew:
    name: bash-completion
    state: latest
  tags:
    - bash
    - pkg

- name: Create ~/.autoload
  file:
    name: ~/.autoload
    state: directory
  tags:
    - bash

- name: Install ~/.bash_profile
  copy:
    src: bash_profile
    dest: ~/.bash_profile
  tags:
    - bash

- name: Install ~/.bashrc
  copy:
    src: bashrc
    dest: ~/.bashrc
  tags:
    - bash
