---
- name: install git
  homebrew:
    name: git
    install_options: with-brewed-curl,with-brewed-openssl
    state: latest
  tags:
    - pkg

- name: install ~/.cvsignore
  copy:
    src: cvsignore
    dest: ~/.cvsignore

- name: install ~/.gitconfig
  template:
    src: gitconfig.j2
    dest: ~/.gitconfig

- name: install bash helpers for a git prompt
  copy:
    src: git-helpers
    dest: ~/.autoload/git-helpers
    mode: '0755'
