---
- name: Update Homebrew
  homebrew:
    update_homebrew: yes
  tags:
    - brew
    - update

- name: Install Packages
  homebrew:
    name: "{{ item }}"
    state: latest
  with_items: "{{ homebrew_packages }}"
  tags:
    - brew
