---
- name: install tmux
  homebrew:
    name: tmux
    state: latest
  tags:
    - tmux
    - pkg

- name: install reattach-to-user-namespace
  homebrew:
    name: reattach-to-user-namespace
    state: latest
  tags:
    - tmux
    - pkg

- name: install tmux package manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: install ~/.tmux.conf
  copy:
    src: tmux.conf
    dest: ~/.tmux.conf
  tags:
    - tmux
