---
- name: install vim
  homebrew:
    name: vim
    state: latest
  tags:
    - pkg
    - vim

- name: create directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - ~/.vim/bundle
    - ~/.vim/backups
    - ~/.vim/swaps
    - ~/.vim/undo
  tags:
    - vim

- name: install plug.vim for managing vim packages
  ignore_errors: True
  get_url:
    url: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    dest: ~/.vim/autoload/plug.vim
  tags:
    - vim

- name: install ~/.vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc
  tags:
    - vim
