---
- name: Install Vim
  homebrew:
    name: vim
    state: latest
  tags:
    - brew

- name: Create Directory
  file:
    name: "{{ item }}"
    state: directory
  with_items:
    - ~/.vim/bundle
    - ~/.vim/backups
    - ~/.vim/swaps
    - ~/.vim/undo

- name: Install NeoBundle for managing vim packages
  git:
    repo: https://github.com/Shougo/neobundle.vim.git 
    dest: ~/.vim/bundle/neobundle.vim

- name: Install ~/.vimrc
  copy:
    src: vimrc
    dest: ~/.vimrc
