---
- name: Install chruby
  homebrew:
    name: chruby
    state: latest
  tags:
    - brew

- name: Install ruby-install
  homebrew:
    name: ruby-install
    state: latest
  tags:
    - brew

- name: Install configuration for rubygems
  copy:
    src: gemrc
    dest: ~/.gemrc
